// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parking_API.Data;

#nullable disable

namespace Parking_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Parking_API.Model.Billing", b =>
            {
                b.Property<int>("BillId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillId"));

                b.Property<decimal?>("Amount")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.Property<int>("BookingId")
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<int?>("DurationInHours")
                    .HasColumnType("int");

                b.Property<int>("ParkingLocationId")
                    .HasColumnType("int");

                b.Property<int>("SlotId")
                    .HasColumnType("int");

                b.Property<bool>("Status")
                    .HasColumnType("bit");

                b.Property<int>("UserId")
                    .HasColumnType("int");

                b.HasKey("BillId");

                b.HasIndex("BookingId");

                b.HasIndex("ParkingLocationId");

                b.HasIndex("SlotId");

                b.HasIndex("UserId");

                b.ToTable("BillingTable");
            });

            modelBuilder.Entity("Parking_API.Model.Booking", b =>
            {
                b.Property<int>("BookingId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                b.Property<int?>("DurationHours")
                    .HasColumnType("int");

                b.Property<DateTime?>("ExitTime")
                    .HasColumnType("datetime2");

                b.Property<bool>("IsPaid")
                    .HasColumnType("bit");

                b.Property<int>("ParkingLocationId")
                    .HasColumnType("int");

                b.Property<int?>("ParkingSlotSlotId")
                    .HasColumnType("int");

                b.Property<int>("SlotId")
                    .HasColumnType("int");

                b.Property<DateTime>("StartTime")
                    .HasColumnType("datetime2");

                b.Property<string>("Status")
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal?>("TotalCost")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.Property<int>("UserId")
                    .HasColumnType("int");

                b.HasKey("BookingId");

                b.HasIndex("ParkingLocationId");

                b.HasIndex("ParkingSlotSlotId");

                b.HasIndex("SlotId");

                b.HasIndex("UserId");

                b.ToTable("BookingTable");
            });

            modelBuilder.Entity("Parking_API.Model.ParkingLocation", b =>
            {
                b.Property<int>("ParkingLocationId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParkingLocationId"));

                b.Property<string>("City")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("TotalSlots")
                    .HasColumnType("int");

                b.HasKey("ParkingLocationId");

                b.ToTable("ParkingLocationTable");
            });

            modelBuilder.Entity("Parking_API.Model.ParkingSlot", b =>
            {
                b.Property<int>("SlotId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlotId"));

                b.Property<int>("ParkingLocationId")
                    .HasColumnType("int");

                b.Property<int>("PricePerHour")
                    .HasColumnType("int");

                b.Property<string>("SlotNumber")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("SlotType")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("Status")
                    .HasColumnType("bit");

                b.HasKey("SlotId");

                b.HasIndex("ParkingLocationId");

                b.ToTable("ParkingSlotTable");
            });

            modelBuilder.Entity("Parking_API.Model.Role", b =>
            {
                b.Property<int>("RoleId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                b.Property<bool>("Active")
                    .HasColumnType("bit");

                b.Property<DateTime>("CreatedTime")
                    .HasColumnType("datetime2");

                b.Property<string>("Roles")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("RoleId");

                b.ToTable("RolesTable");
            });

            modelBuilder.Entity("Parking_API.Model.Users", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<bool>("Active")
                    .HasColumnType("bit");

                b.Property<string>("ConfirmPassword")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("MobileNumber")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Password")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("RoleId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("RoleId");

                b.ToTable("UsersTable");
            });

            modelBuilder.Entity("Parking_API.Model.VehicleEntryExit", b =>
            {
                b.Property<int>("id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                b.Property<double?>("BillAmount")
                    .HasColumnType("float");

                b.Property<DateTime>("EntryTime")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("ExitTime")
                    .HasColumnType("datetime2");

                b.Property<int>("parkingSlotId")
                    .HasColumnType("int");

                b.Property<string>("vehicleNumber")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("vehicleType")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("id");

                b.HasIndex("parkingSlotId");

                b.ToTable("VehicleEntryExitTable");
            });

            modelBuilder.Entity("Parking_API.Model.Billing", b =>
            {
                b.HasOne("Parking_API.Model.Booking", "Booking")
                    .WithMany()
                    .HasForeignKey("BookingId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Parking_API.Model.ParkingLocation", "ParkingLocation")
                    .WithMany()
                    .HasForeignKey("ParkingLocationId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Parking_API.Model.ParkingSlot", "ParkingSlot")
                    .WithMany()
                    .HasForeignKey("SlotId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Parking_API.Model.Users", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Booking");

                b.Navigation("ParkingLocation");

                b.Navigation("ParkingSlot");

                b.Navigation("User");
            });

            modelBuilder.Entity("Parking_API.Model.Booking", b =>
            {
                b.HasOne("Parking_API.Model.ParkingLocation", "ParkingLocation")
                    .WithMany()
                    .HasForeignKey("ParkingLocationId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Parking_API.Model.ParkingSlot", "ParkingSlot")
                    .WithMany()
                    .HasForeignKey("ParkingSlotSlotId");

                b.HasOne("Parking_API.Model.Users", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("ParkingLocation");

                b.Navigation("ParkingSlot");

                b.Navigation("User");
            });

            modelBuilder.Entity("Parking_API.Model.ParkingSlot", b =>
            {
                b.HasOne("Parking_API.Model.ParkingLocation", "ParkingLocation")
                    .WithMany("ParkingSlots")
                    .HasForeignKey("ParkingLocationId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("ParkingLocation");
            });

            modelBuilder.Entity("Parking_API.Model.Users", b =>
            {
                b.HasOne("Parking_API.Model.Role", "Role")
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Role");
            });

            modelBuilder.Entity("Parking_API.Model.VehicleEntryExit", b =>
            {
                b.HasOne("Parking_API.Model.ParkingSlot", "ParkingSlot")
                    .WithMany()
                    .HasForeignKey("parkingSlotId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("ParkingSlot");
            });

            modelBuilder.Entity("Parking_API.Model.ParkingLocation", b =>
            {
                b.Navigation("ParkingSlots");
            });
#pragma warning restore 612, 618
        }
    }
}
